package com.maxipalacios.taxes;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for the cluster-free surface of the job:
 *
 * <ul>
 *     <li>the {@code --certification-period} submission flag parser (issue
 *         #7) — the spec VALUE itself is validated downstream by
 *         {@link CertificationPeriodTest}; these tests pin the command-line
 *         grammar: the flag is optional (env decides), both the separated and
 *         '=' forms work, and anything else on the command line fails fast
 *         with the usage message instead of being silently ignored;</li>
 *     <li>the fail-fast validation of {@link PipelineConfig} and
 *         {@link DbConnection}: every field the DDL interpolates is
 *         allow-listed or rejected at construction, so a hostile or
 *         misconfigured value can never reach the connector DDL;</li>
 *     <li>the certification period boundary SQL generated by
 *         {@code TaxJob.createConsolidationInsertSql}: fixed-second periods
 *         align to session-zone wall-clock multiples of n (issue #1 story
 *         #14), while the demo sizes whose shift cancels emit the plain
 *         epoch-floor formula byte-identically.</li>
 * </ul>
 */
class TaxJobTest {

    // ------------------------------------------------------------------
    // --certification-period argument parsing
    // ------------------------------------------------------------------

    @Test
    void returnsNullForAnEmptyCommandLineSoTheEnvVarDecides() {
        assertNull(TaxJob.certificationPeriodArg(new String[0]));
    }

    @Test
    void acceptsTheSeparatedForm() {
        assertEquals("daily", TaxJob.certificationPeriodArg(new String[]{"--certification-period", "daily"}));
        assertEquals("60s", TaxJob.certificationPeriodArg(new String[]{"--certification-period", "60s"}));
    }

    @Test
    void acceptsTheEqualsForm() {
        assertEquals("monthly", TaxJob.certificationPeriodArg(new String[]{"--certification-period=monthly"}));
        assertEquals("1s", TaxJob.certificationPeriodArg(new String[]{"--certification-period=1s"}));
    }

    @Test
    void rejectsAnUnknownFlag() {
        IllegalArgumentException thrown =
                assertThrows(IllegalArgumentException.class, () -> TaxJob.certificationPeriodArg(new String[]{"--period", "daily"}));
        assertEquals(TaxJob.USAGE, thrown.getMessage());
    }

    @Test
    void rejectsATrailingExtraArgumentInsteadOfIgnoringIt() {
        IllegalArgumentException thrown = assertThrows(IllegalArgumentException.class,
                () -> TaxJob.certificationPeriodArg(new String[]{"--certification-period", "daily", "extra"}));
        assertEquals(TaxJob.USAGE, thrown.getMessage());
    }

    @Test
    void rejectsAFlagWithoutAValue() {
        IllegalArgumentException thrown =
                assertThrows(IllegalArgumentException.class, () -> TaxJob.certificationPeriodArg(new String[]{"--certification-period"}));
        assertEquals(TaxJob.USAGE, thrown.getMessage());
    }

    @Test
    void rejectsAnEmptyValueInBothForms() {
        IllegalArgumentException equalsForm =
                assertThrows(IllegalArgumentException.class, () -> TaxJob.certificationPeriodArg(new String[]{"--certification-period="}));
        assertEquals(TaxJob.USAGE, equalsForm.getMessage());
        IllegalArgumentException separatedForm =
                assertThrows(IllegalArgumentException.class, () -> TaxJob.certificationPeriodArg(new String[]{"--certification-period", ""}));
        assertEquals(TaxJob.USAGE, separatedForm.getMessage());
    }

    /**
     * Pins {@link TaxJob#CHECKPOINT_INTERVAL_MS} at the 10-second interval
     * issue #8's acceptance criterion requires ("checkpointing remains
     * enabled at 10-second intervals"). Honest scope: a cluster-free unit
     * test can only pin the constant's VALUE — that the pipeline really
     * checkpoints (and recovers from its checkpoints) at this interval is
     * what {@code CheckpointRecoveryE2eTest} proves against the real mini
     * cluster.
     */
    @Test
    void pinsTheProductionCheckpointInterval() {
        assertEquals(10_000L, TaxJob.CHECKPOINT_INTERVAL_MS);
    }

    // ------------------------------------------------------------------
    // DbConnection / PipelineConfig fail-fast validation (the values the
    // DDL builders interpolate)
    // ------------------------------------------------------------------

    /** A valid connection shaped like the e2e tests' Testcontainers coordinates. */
    private static DbConnection testConnection() {
        return new DbConnection("localhost", "32768", "flink", "flink", "taxes");
    }

    /** A valid config shaped like the e2e tests' constructor calls. */
    private static PipelineConfig testConfig(String slotName) {
        return new PipelineConfig(testConnection(), testConnection(), slotName, CertificationPeriod.parse("60s"));
    }

    @Test
    void acceptsDockerServiceNamesLocalhostIpsAndTestcontainersCoordinates() {
        for (String host : new String[]{"postgres-source", "postgres-target", "localhost", "127.0.0.1", "172.18.0.5"}) {
            DbConnection connection = new DbConnection(host, "5432", "flink_cdc", "flink", "taxes");
            assertEquals(host, connection.host());
        }
        // Typical ephemeral Testcontainers mapped ports are five digits.
        assertEquals("32768", testConnection().port());
    }

    @Test
    void acceptsTheBoundaryPorts() {
        assertEquals("1", new DbConnection("localhost", "1", "flink", "flink", "taxes").port());
        assertEquals("65535", new DbConnection("localhost", "65535", "flink", "flink", "taxes").port());
    }

    @Test
    void rejectsAQuoteBearingPassword() {
        for (String password : new String[]{"flink'1", "flink\\x", "flink;drop", "flink\nnewline", "flink\rcr"}) {
            IllegalArgumentException thrown = assertThrows(IllegalArgumentException.class,
                    () -> new DbConnection("localhost", "5432", "flink", password, "taxes"),
                    "password <" + password + "> must be rejected");
            assertTrue(thrown.getMessage().contains("password"), thrown.getMessage());
        }
    }

    @Test
    void rejectsAQuoteInTheHost() {
        for (String host : new String[]{"postgres-source'", "post'gres", "host\"x", "host;x", "host\nx", "host x"}) {
            assertThrows(IllegalArgumentException.class,
                    () -> new DbConnection(host, "5432", "flink", "flink", "taxes"),
                    "host <" + host + "> must be rejected");
        }
    }

    @Test
    void rejectsAnOutOfRangeOrNonNumericPort() {
        for (String port : new String[]{"0", "65536", "-1", "5432a", " 5432", "+5432", "", "65 535"}) {
            assertThrows(IllegalArgumentException.class,
                    () -> new DbConnection("localhost", port, "flink", "flink", "taxes"),
                    "port <" + port + "> must be rejected");
        }
    }

    @Test
    void rejectsIdentifierFieldsOutsideTheAllowList() {
        for (String username : new String[]{"flink user", "flink'user", "flink-user", ""}) {
            assertThrows(IllegalArgumentException.class,
                    () -> new DbConnection("localhost", "5432", username, "flink", "taxes"),
                    "username <" + username + "> must be rejected");
        }
        for (String database : new String[]{"taxes db", "taxes;db", ""}) {
            assertThrows(IllegalArgumentException.class,
                    () -> new DbConnection("localhost", "5432", "flink", "flink", database),
                    "database <" + database + "> must be rejected");
        }
    }

    @Test
    void rejectsASlotNameWithUppercaseOrOverTheLengthCap() {
        for (String slot : new String[]{"Flink_tax_certificates", "flinkTaxCertificates", "a".repeat(64), "flink-tax", ""}) {
            assertThrows(IllegalArgumentException.class, () -> testConfig(slot),
                    "slot name <" + slot + "> must be rejected");
        }
    }

    @Test
    void rejectsANullCertificationPeriod() {
        assertThrows(IllegalArgumentException.class,
                () -> new PipelineConfig(testConnection(), testConnection(), "flink_tax_certificates", null));
    }

    @Test
    void withCertificationPeriodParsesTheNewSpecIntoTheCopy() {
        PipelineConfig cfg = testConfig("flink_tax_certificates");
        PipelineConfig daily = cfg.withCertificationPeriod("daily");
        assertEquals(CertificationPeriod.Kind.CALENDAR_DAY, daily.certificationPeriod().kind());
        assertEquals(cfg.source(), daily.source());
        assertEquals(cfg.replicationSlotName(), daily.replicationSlotName());
        // The copy keeps the original untouched.
        assertEquals(CertificationPeriod.Kind.SECONDS, cfg.certificationPeriod().kind());
    }

    @Test
    void withCertificationPeriodRejectsAnInvalidSpec() {
        PipelineConfig cfg = testConfig("flink_tax_certificates");
        assertThrows(IllegalArgumentException.class, () -> cfg.withCertificationPeriod("5m"));
        assertThrows(IllegalArgumentException.class, () -> cfg.withCertificationPeriod("0s"));
    }

    @Test
    void derivesTheMerchantsSlotNameByAppendingTheSuffix() {
        assertEquals("flink_tax_certificates_merchants",
                testConfig("flink_tax_certificates").merchantsReplicationSlotName());
    }

    @Test
    void rejectsABaseSlotNameWhoseMerchantsSuffixWouldBreakTheSlotRules() {
        // 54 chars is a legal base name, but "_merchants" pushes the derived
        // value over PostgreSQL's 63-char cap: the derivation must fail fast.
        PipelineConfig cfg = testConfig("a".repeat(54));
        assertThrows(IllegalStateException.class, cfg::merchantsReplicationSlotName);
    }

    // ------------------------------------------------------------------
    // Certification period boundary SQL (issue #1 story #14: fixed-second
    // periods align to the session zone's wall clock)
    // ------------------------------------------------------------------

    // The GROUP BY key the SECONDS path generated before local alignment:
    // the event's epoch seconds floored to a multiple of n.
    private static String plainEpochFloor(long n) {
        return "CAST(FLOOR(UNIX_TIMESTAMP(DATE_FORMAT(CAST(calc.created_at AS TIMESTAMP(3)), "
                + "'yyyy-MM-dd HH:mm:ss')) / " + n + ") * " + n + " AS BIGINT)";
    }

    // The aligned GROUP BY key: floor in local-wall-clock coordinates (the
    // zone's offset in seconds is subtracted first, Buenos Aires -03:00 =
    // -10800), then shift the boundary back to an epoch.
    private static String localAlignedEpochFloor(long n, long offsetSeconds) {
        return "CAST(FLOOR((UNIX_TIMESTAMP(DATE_FORMAT(CAST(calc.created_at AS TIMESTAMP(3)), "
                + "'yyyy-MM-dd HH:mm:ss'))" + (offsetSeconds < 0 ? " - " + -offsetSeconds : " + " + offsetSeconds)
                + ") / " + n + ") * " + n + (offsetSeconds < 0 ? " + " + -offsetSeconds : " - " + offsetSeconds)
                + " AS BIGINT)";
    }

    /**
     * The demo sizes (60s, and the 1s/2s the e2e suite exercises) divide
     * Buenos Aires' -10800s offset, so the local-alignment shift cancels
     * algebraically: the generated SQL stays byte-identical to the previous
     * epoch-floor formula and the boundaries are unchanged.
     */
    @Test
    void secondsPeriodsDividingTheZoneOffsetKeepThePreviousFormulaByteIdentically() {
        for (long n : new long[]{1, 2, 60}) {
            String sql = TaxJob.createConsolidationInsertSql(CertificationPeriod.parse(n + "s"), TaxJob.SESSION_ZONE);
            assertTrue(sql.contains(plainEpochFloor(n)),
                    "the " + n + "s GROUP BY key must stay the plain epoch floor, got:\n" + sql);
            // No leaked shift anywhere in the statement (the offset interval
            // literal renders as '-3:0' HOUR TO MINUTE, never as 10800).
            assertFalse(sql.contains("10800"), "the " + n + "s SQL must carry no shift, got:\n" + sql);
        }
    }

    /**
     * A period that does NOT divide the zone offset (7s, 11s — note 45s
     * divides 10800, so it takes the plain form) must align to local
     * wall-clock multiples of n: the GROUP BY key floors in local-wall-clock
     * coordinates (epoch shifted by the zone's fixed offset) and shifts the
     * boundary back, so a 7s period starts at Buenos Aires 00:00:00,
     * 00:00:07, 00:00:14, ... instead of epoch multiples of 7.
     */
    @Test
    void secondsPeriodsNotDividingTheZoneOffsetAlignToLocalWallClock() {
        for (long n : new long[]{7, 11}) {
            String sql = TaxJob.createConsolidationInsertSql(CertificationPeriod.parse(n + "s"), TaxJob.SESSION_ZONE);
            assertTrue(sql.contains(localAlignedEpochFloor(n, -10800)),
                    "the " + n + "s GROUP BY key must floor in Buenos Aires wall-clock coordinates, got:\n" + sql);
            // The window still spans exactly n seconds.
            assertTrue(sql.contains("+ INTERVAL '" + n + "' SECOND"), sql);
        }
    }

    /** The calendar kinds are untouched by the SECONDS alignment. */
    @Test
    void calendarPeriodsKeepTheirSessionWallClockFloors() {
        String daily = TaxJob.createConsolidationInsertSql(CertificationPeriod.parse("daily"), TaxJob.SESSION_ZONE);
        assertTrue(daily.contains("FLOOR(CAST(calc.created_at AS TIMESTAMP(3)) TO DAY)"), daily);
        assertTrue(daily.contains("+ INTERVAL '1' DAY"), daily);
        String monthly = TaxJob.createConsolidationInsertSql(CertificationPeriod.parse("monthly"), TaxJob.SESSION_ZONE);
        assertTrue(monthly.contains("FLOOR(CAST(calc.created_at AS TIMESTAMP(3)) TO MONTH)"), monthly);
        assertTrue(monthly.contains("+ INTERVAL '1' MONTH"), monthly);
    }
}
